"use client"

import { useState } from "react"
import { Activity, ArrowRight, ShieldCheck, Sparkles } from "lucide-react"

import { PredictionForm } from "@/components/prediction/PredictionForm"
import { PredictionResult } from "@/components/prediction/PredictionResult"
import { predict } from "@/lib/api"
import type {
  PredictionRequest,
  PredictionResponse,
} from "@/types/prediction"

export default function PredictPage() {
  const [result, setResult] = useState<PredictionResponse | null>(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)

  async function handlePrediction(data: PredictionRequest) {
    setLoading(true)
    setError(null)
    setResult(null)

    try {
      const response = await predict(data)
      setResult(response)
    } catch (err) {
      setError(
        err instanceof Error
          ? err.message
          : "Something went wrong while making the prediction."
      )
    } finally {
      setLoading(false)
    }
  }

  return (
    <main className="min-h-screen">
      <section className="mx-auto max-w-6xl px-4 py-8 sm:px-6 lg:px-8">
        {/* Header */}
        <div className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
          <div>
            <div className="mb-2 flex items-center gap-2">
              <span className="font-mono text-[10px] font-semibold uppercase tracking-[0.16em] text-primary">
                01 / Prediction
              </span>
              <span className="h-px w-6 bg-primary/40" />
              <span className="text-[10px] text-muted-foreground">
                ML inference
              </span>
            </div>

            <h1 className="text-2xl font-bold tracking-tight sm:text-3xl">
              Medical Cost Prediction
            </h1>

            <p className="mt-2 max-w-xl text-sm leading-6 text-muted-foreground">
              Enter patient information and let the trained machine learning
              model estimate the medical insurance charges.
            </p>
          </div>

          <div className="hidden items-center gap-2 rounded-lg border bg-card px-3 py-2 sm:flex">
            <Activity className="h-4 w-4 text-primary" />
            <span className="text-[11px] font-medium">Model Ready</span>
          </div>
        </div>

        {/* Main console */}
        <div className="grid gap-5 lg:grid-cols-[1.15fr_0.85fr]">
          {/* Form */}
          <section className="rounded-2xl border bg-card p-5 shadow-sm sm:p-6">
            <div className="mb-5 flex items-center justify-between border-b pb-4">
              <div>
                <h2 className="text-sm font-semibold">Patient Information</h2>
                <p className="mt-1 text-[11px] text-muted-foreground">
                  Provide the six model input features.
                </p>
              </div>

              <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-primary/10">
                <Sparkles className="h-4 w-4 text-primary" />
              </div>
            </div>

            <PredictionForm
              onSubmit={handlePrediction}
              loading={loading}
            />
          </section>

          {/* Result */}
          <section className="rounded-2xl border bg-card p-5 shadow-sm sm:p-6">
            <div className="mb-5 flex items-center justify-between border-b pb-4">
              <div>
                <h2 className="text-sm font-semibold">Prediction Result</h2>
                <p className="mt-1 text-[11px] text-muted-foreground">
                  Output generated by the ML pipeline.
                </p>
              </div>

              <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-primary/10">
                <ShieldCheck className="h-4 w-4 text-primary" />
              </div>
            </div>

            <PredictionResult
              result={result}
              loading={loading}
              error={error}
            />
          </section>
        </div>

        {/* Bottom info */}
        <div className="mt-5 flex flex-col gap-2 rounded-xl border bg-muted/20 px-4 py-3 sm:flex-row sm:items-center sm:justify-between">
          <div className="flex items-center gap-2">
            <span className="h-1.5 w-1.5 rounded-full bg-primary" />
            <span className="text-[10px] text-muted-foreground">
              Powered by a scikit-learn Random Forest regression pipeline
            </span>
          </div>

          <div className="flex items-center gap-1 text-[10px] text-muted-foreground">
            <span>FastAPI</span>
            <ArrowRight className="h-3 w-3" />
            <span>ML Model</span>
          </div>
        </div>
      </section>
    </main>
  )
}